### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by GamerMJay** [Shelly7w7/TotemJoin#1]
Hey, can you please Update TotemJoin to PM4? 😅

**Comment by Shelly7w7** [comment]
I forgot about this plugin, I will get right to it.

**Comment by GamerMJay** [comment]
Thank you 😄

**Comment by Shelly7w7** [comment]
@GamerMJay Updated to 4,0. Download the phar [here](https://poggit.pmmp.io/ci/Shelly7w7/TotemJoin/TotemJoin)
